#-----------------------------------------------------------------------------------------
#
# Сборка и деплой бэкенда thousandwords
# 
#-----------------------------------------------------------------------------------------

name: deploy thousandwords

on:
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**'
jobs:

  build_and_deploy_backend:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@master
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - 
        name: Build
        run: |
          cd backend
          docker build -t backend-api .
      - 
        name: TAG
        run: docker tag backend-api ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest
      - 
        name: Push docker image
        run: docker push ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest
