#-----------------------------------------------------------------------------------------
#
# Сборка и деплой проекта thousandwords
# 
#-----------------------------------------------------------------------------------------

name: deploy thousandwords

on:
  push:
    branches:
      - 'master'
jobs:

  # build_and_deploy_backend:

  #   runs-on: ubuntu-latest
    
  #   steps:
  #     -
  #       name: Checkout 
  #       uses: actions/checkout@master
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_LOGIN }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #     - 
  #       name: Build
  #       run: |
  #         cd backend
  #         docker build -t backend-api .
  #     - 
  #       name: TAG
  #       run: docker tag backend-api ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest
  #     - 
  #       name: Push docker image
  #       run: docker push ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest


    build_and_deploy_static:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@master

      - name: copy file via ssh password
        uses: ./
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PWD }}
          # source: "tests/a.txt,tests/b.txt"
          source: "./devops/prod/nginx.conf"
          target: "~/"
