#-----------------------------------------------------------------------------------------
#
# Сборка и деплой проекта thousandwords
# 
#-----------------------------------------------------------------------------------------

name: deploy thousandwords

on:
  push:
    branches:
      - 'master'
jobs:

  # build_and_deploy_backend:

  #   runs-on: ubuntu-latest
    
  #   steps:
  #     -
  #       name: Checkout 
  #       uses: actions/checkout@master
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_LOGIN }}
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  #     - 
  #       name: Build
  #       run: |
  #         cd backend
  #         docker build -t backend-api .
  #     - 
  #       name: TAG
  #       run: docker tag backend-api ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest
  #     - 
  #       name: Push docker image
  #       run: docker push ${{ secrets.DOCKER_LOGIN }}/thousandwords:latest


  build_and_deploy_static:
    name: Build
    runs-on: ubuntu-latest

    # strategy: # Это стратегия запусков
    #   matrix: # Запускать это задание с разными параметрами
    #     node-version: [18.x] # Версии ноды

    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Run a multi-line script
      run: |
        cp ./devops/prod/nginx.conf ./
        cp ./devops/prod/docker-compose.yml ./


    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "18.x"

    - name: Install dependencies
      run: |
        ls
        echo "ls"
        cd frontend
        npm install
        npm run build
        ls

    - name: Run a multi-line script
      run: |
        ls
        cd ..
        cp -aT /frontend/build /
        ls

        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        source: "./nginx.conf,build,docker-compose.yml"
        target: "~/"
        overwrite: true
