#-----------------------------------------------------------------------------------------
#
# Сборка и деплой конфигураций thousandwords
# 
#-----------------------------------------------------------------------------------------

name: deploy config thousandwords

on:
  push:
    branches:
      - 'master'
    paths:
      - 'devops/**'

jobs:

  deploy_config:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: copy config
      run: |
        cp -r ./devops/prod ./
        
    - name: send config on server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        source: "prod"
        target: "~/"
        overwrite: true

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        script: 'source ~/remote_profile && echo $DOCKER_LOGIN && echo $DOCKER_PWD'


    
