#-----------------------------------------------------------------------------------------
#
# Сборка и деплой фронтенда thousandwords
# 
#-----------------------------------------------------------------------------------------

name: deploy front thousandwords

on:
  push:
    branches:
      - 'master'
    paths:
      - 'frontend/**'

jobs:

  build_and_deploy_static:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: use node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "18.x"

    - name: install, build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: copy static
      run: |
        cp -r ./frontend/build ./
        
    - name: send static on server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        source: "build"
        target: "~/"
        overwrite: true
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PWD }}
        script: 'source ~/remote_profile && cd prod && bash deploy.bash'
